CREATE DATABASE django WITH ENCODING 'UTF8' LC_COLLATE='ru_RU.UTF8' LC_CTYPE='ru_RU.UTF8' TEMPLATE=template0;
CREATE USER django WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE django TO django;
